version: "3.9"

services:
  user:
    container_name: user
    build:
      context: ./user
      dockerfile: ./Dockerfile
      args:
        - NAME=user

  product:
    container_name: product
    build:
      context: ./product
      dockerfile: ./Dockerfile
      args:
        - NAME=product
