version: "3.9"

services:
  user:
    ports:
      - 5000:5000
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: $DATABASE_URL_USER
    volumes:
      - ./user:/user

  product:
    ports:
      - 5001:5000
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: $DATABASE_URL_PRODUCT
    volumes:
      - ./product:/product
  postgres:
    image: postgres:13.2-alpine
    build: ./postgres
    container_name: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
        POSTGRES_PASSWORD: "postgres"
        POSTGRES_MULTIPLE_DATABASES: users, products
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
