version: "3.9"

services:
  user:
    ports:
      - 5001:5000
    volumes:
      - type: bind
        source: ./user
        target: /user

  product:
    ports:
      - 5002:5000
    environment:
      DATABASE_URL: $DATABASE_URL_PRODUCT
    volumes:
      - type: bind
        source: ./product
        target: /product

#  order:
#    ports:
#      - 5002:5000
#    depends_on:
#      postgres:
#        condition: service_healthy
#    environment:
#      DATABASE_URL: $DATABASE_URL_ORDER
#    volumes:
#      - type: bind
#        source: ./order
#        target: /order

