version: "3.9"

services:
  user:
    ports:
      - 5000:5000
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: $DATABASE_URL_USER
    volumes:
      - type: bind
        source: ./user
        target: /user

  product:
    ports:
      - 5001:5000
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: $DATABASE_URL_PRODUCT
    volumes:
      - type: bind
        source: ./product
        target: /product

  order:
    ports:
      - 5002:5000
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: $DATABASE_URL_ORDER
    volumes:
      - type: bind
        source: ./order
        target: /order

  postgres:
    image: postgres:13.2-alpine
    build: ./postgres
    container_name: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
        POSTGRES_PASSWORD: "postgres"
        POSTGRES_MULTIPLE_DATABASES: users, products, orders
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

