version: "3.9"

services:
  user:
    container_name: user
    build:
      context: ./user
      dockerfile: ./Dockerfile
      args:
        - NAME=user
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://user:5000/graphql || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./user:/user
    ports:
      - 5001:5000

  product:
    container_name: product
    build:
      context: ./product
      dockerfile: ./Dockerfile
      args:
        - NAME=product
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://product:5000/graphql || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./product:/product
    ports:
      - 5002:5000

  order:
    container_name: order
    build:
      context: ./order
      dockerfile: ./Dockerfile
      args:
        - NAME=order
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://order:5000/graphql || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./order:/order
    ports:
      - 5003:5000

  gateway:
    container_name: gateway
    build:
      context: ./gateway
      dockerfile: ./Dockerfile
    volumes:
      - ./gateway:/app:rw,cached
      - gateway_modules:/app/node_modules
    ports:
      - "4000:80"
    depends_on:
      user:
        condition: service_healthy

volumes:
  gateway_modules: ~
